# Partie 1 : Chargement et exploration initiale

Dans cette partie, nous allons charger le dataset et observer sa structure générale.
### Affichage des premières lignes
Permet de visualiser un aperçu des données.

In [1]:
import pandas as pd
df = pd.read_csv("../data/Teen_Mental_Health_Dataset.csv")
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

### Affichage des dernières lignes
Permet de vérifier la fin du dataset.
### Dimensions du dataset
Nombre de lignes et de colonnes.
### Types des variables
Identifier les types (int, float, object…).
### Informations générales
Résumé complet du dataset.

### Statistiques descriptives
Résumé des variables numériques.

In [2]:
df.tail()
df.shape
df.dtypes
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   str
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   str
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   str
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), str(3)
memory usage: 140.4 KB

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000

### Vérification des doublons
Nombre de lignes dupliquées.

In [3]:
df.duplicated().sum()

np.int64(0)

### Suppression des doublons

In [4]:
df=df.drop_duplicates()

### Valeurs manquantes
Nombre de valeurs nulles par colonne.

In [5]:
df.isnull().sum()

age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
dtype: int64

### Suppression des valeurs manquantes

In [6]:
df.dropna()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

### Remplacement des valeurs manquantes
- Moyenne pour les variables numériques
- Mode pour les variables catégorielles

In [7]:
df.fillna(df.mean(numeric_only=True))

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [8]:
df.fillna(df.mode().iloc[0])

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

### Filtrage simple
Personnes avec âge > 16

In [9]:
df[df["age"] > 16]

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
6,18,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2,2,5,0
8,19,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1,10,9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1188,17,female,7.4,Instagram,7.4,2.0,3.76,1.7,high,10,1,4,0
1190,17,female,3.8,Instagram,8.4,0.9,3.60,1.9,high,1,2,2,0
1191,19,male,8.0,TikTok,4.7,0.5,2.18,0.6,medium,8,8,6,1
1194,17,male,2.0,Both,4.5,1.7,2.65,0.0,medium,9,4,2,0
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0

### Filtrage avec condition multiple

In [10]:
df[(df["age"] > 16) & (df["daily_social_media_hours"] > 4)]

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
5,19,female,7.4,Both,4.4,2.4,2.63,0.6,high,3,5,7,0
13,17,female,6.8,TikTok,5.7,1.1,3.29,1.3,medium,1,10,10,0
21,18,male,4.1,Both,7.4,2.4,2.38,1.5,medium,8,4,9,0
22,18,male,5.3,Instagram,4.9,1.2,3.69,1.2,low,5,4,5,0
35,17,female,5.0,Both,4.9,2.1,2.01,1.0,low,9,4,9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1181,18,male,4.1,Instagram,6.7,2.1,2.50,0.1,medium,8,1,5,0
1183,19,female,6.6,Both,9.0,2.9,2.47,1.7,medium,3,7,9,0
1188,17,female,7.4,Instagram,7.4,2.0,3.76,1.7,high,10,1,4,0
1191,19,male,8.0,TikTok,4.7,0.5,2.18,0.6,medium,8,8,6,1
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0

### Filtrage par catégories

In [11]:
df[df["gender"].isin(["Male", "Female"])]

Empty DataFrame
Columns: [age, gender, daily_social_media_hours, platform_usage, sleep_hours, screen_time_before_sleep, academic_performance, physical_activity, social_interaction_level, stress_level, anxiety_level, addiction_level, depression_label]
Index: []

### Tri par âge

In [12]:
df.sort_values(by="age")

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
16,13,male,1.5,Both,4.2,1.4,2.59,0.5,high,4,5,8,0
821,13,female,4.3,TikTok,4.4,0.9,2.35,1.5,high,3,1,7,0
830,13,male,5.9,TikTok,6.6,2.6,3.58,1.6,medium,7,7,10,0
866,13,male,7.7,Instagram,4.4,2.0,3.09,1.0,high,8,7,8,1
47,13,female,3.5,Instagram,5.1,1.1,2.27,1.8,medium,2,5,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1184,19,male,1.4,Both,4.5,2.3,3.90,0.0,medium,2,8,10,0
81,19,female,4.8,TikTok,6.0,1.5,2.61,1.2,high,2,2,6,0
64,19,female,7.9,TikTok,5.1,1.7,2.80,0.8,low,6,1,8,0
1163,19,male,4.0,Instagram,7.8,0.6,3.61,1.7,high,2,7,9,0
1159,19,female,7.3,Instagram,7.8,1.0,2.91,0.8,medium,9,7,5,0

In [13]:
df.sort_values(by="daily_social_media_hours", ascending=False)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
404,13,male,8.0,Instagram,6.9,2.5,2.45,1.7,medium,10,1,3,0
313,13,female,8.0,Instagram,5.4,2.8,3.10,1.9,high,6,10,10,0
369,13,male,8.0,Both,8.9,2.2,3.82,1.2,low,8,8,4,0
764,18,female,8.0,TikTok,4.3,0.8,3.44,0.8,medium,3,4,4,0
783,17,male,8.0,Instagram,6.9,2.2,2.36,1.6,low,4,2,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,13,male,1.1,TikTok,7.1,1.8,2.55,0.8,high,5,5,10,0
731,18,male,1.0,Instagram,7.1,0.8,2.47,1.9,high,4,2,4,0
397,14,female,1.0,Both,6.6,1.4,2.02,1.9,low,6,5,5,0
713,15,male,1.0,TikTok,8.5,2.0,3.77,1.9,high,4,1,7,0
453,16,female,1.0,Both,4.1,1.3,2.22,0.4,low,2,1,8,0

### Distribution du genre

In [14]:
df["gender"].value_counts()

gender
male      615
female    585
Name: count, dtype: int64

### Distribution en pourcentage

In [15]:
df["gender"].value_counts(normalize=True)

gender
male      0.5125
female    0.4875
Name: proportion, dtype: float64

### Moyenne du temps sur réseaux sociaux par genre

In [16]:
df.groupby("gender")["daily_social_media_hours"].mean()

gender
female    4.512991
male      4.559187
Name: daily_social_media_hours, dtype: float64

### Moyenne du sommeil par niveau de stress

In [17]:
df.groupby("stress_level")["sleep_hours"].mean()

stress_level
1     6.527612
2     6.426852
3     6.340517
4     6.498561
5     6.617829
6     6.342982
7     6.403774
8     6.367308
9     6.443443
10    6.467187
Name: sleep_hours, dtype: float64

### Moyenne du sommeil par niveau de stress

In [18]:
df.groupby(["gender", "stress_level"])["daily_social_media_hours"].mean()

gender  stress_level
female  1               4.295385
        2               4.395000
        3               5.049153
        4               3.990625
        5               4.087719
        6               4.546667
        7               4.453488
        8               4.566000
        9               4.530645
        10              5.190769
male    1               4.872464
        2               4.289583
        3               4.643860
        4               4.618667
        5               4.350000
        6               4.251852
        7               4.665079
        8               4.885185
        9               4.495000
        10              4.452381
Name: daily_social_media_hours, dtype: float64

## Conclusion rapide

Cette exploration prepare le terrain pour les visualisations plus avancees. Elle aide a identifier les profils les plus exposes, les indicateurs a suivre et les relations a mettre en avant dans le dashboard final.